### ISSUE TITLE
Unicode characters in user names

### ISSUE THREAD

**Issue by swthorn** [iandwelker/smcurser#1]
Hi,

This line: 
https://github.com/iandwelker/smcurser/blob/db4cc99981627e598a3a36594aa7f9c865cf418f/src/chats_view.rs#L122

may cause issues with Unicode bytes. Specifically, I'm having this panic when my terminal is not full screen when I name people ending in an emoji. Making my terminal fullscreen does not have this issue.

![image](https://user-images.githubusercontent.com/62764299/111222120-c83bcd00-85b1-11eb-97d3-940b81836e99.png)

I'm thinking this -3 you have in place may not work if the name ends in unicode, since you can't predict the size of a character

**Comment by swthorn** [comment]
Solved in d84456574346be1477f7a876234ae8f5fd6c71a2

**Comment by itsjunetime** [comment]
Thanks for closing it; I was going to wait until I had a new release compiled to comment but it looks like it's working well for you, so I don't have to.
