### ISSUE TITLE
Readme links are incorrect

### ISSUE THREAD

**Issue by lmburns** [iandwelker/smcurser#3]
The link you have points to `ianwelker/smserver`, when your username is `iandwelker/smserver`

Just wanted to let you know

**Comment by itsjunetime** [comment]
Fixed [here](https://github.com/iandwelker/smcurser/commit/cadffd5da9c00a982b9b92263c23b3ca19cd6e05) and [here](https://github.com/iandwelker/smcurser/commit/8252ccd2e1942dd7f628ed05dfe6533331bb99ed) &mdash; thanks for pointing that out!
